// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gamma_r_cpp
double gamma_r_cpp(NumericVector pars, int r, NumericVector parGrp);
RcppExport SEXP _RASCHplot_gamma_r_cpp(SEXP parsSEXP, SEXP rSEXP, SEXP parGrpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parGrp(parGrpSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_r_cpp(pars, r, parGrp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RASCHplot_gamma_r_cpp", (DL_FUNC) &_RASCHplot_gamma_r_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RASCHplot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
