# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_r_cpp <- function(pars, r, parGrp) {
    .Call(`_RASCHplot_gamma_r_cpp`, pars, r, parGrp)
}

